BackofficeCar/BackofficeCar/Controllers/ManageUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BackofficeCar.Controllers
{
    public class ManageUsersController : Controller
    {
        //
        // GET: /ManageUsers/

        public ActionResult Index()
        {
            return View();
        }

    }
}

BackofficeCar/BackofficeCar/Controllers/ManageVehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BackofficeCar.DbHelper;
using BackofficeRent.Model;

namespace BackofficeCar.Controllers
{
    public class ManageVehiclesController : Controller
    {
        //
        // GET: /ManageVehicles/

        public ActionResult Index()
        {
            var DAL = new DAL();
            var list = DAL.GetAllVehicles();
            return View(list);
        }
        public ActionResult Edit(int id)
        {
            if(id<=0) throw  new Exception("Invalid id, please pass valid vehicle id.");
            var DAL = new DAL();
            var obj = DAL.GetVehicleById(id);
            if (obj == null) throw new Exception("No vehicle found");

            return View("Details", obj);
        }
        /// <summary>
        /// TODO: Image Upload
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(VehicleDetailsDto model)
        {
            if (model== null || (model.VehicleID ?? 0) <= 0) throw new Exception("Bad format data passed.");
            
            var DAL = new DAL();
            var obj = DAL.UpdateVehicle(model.VehicleID.Value, model);
            if (obj == null || obj.IsError) throw new Exception(obj == null ? "Null exception occurred" : obj.Message?? "");

            return View("Details", (VehicleDetailsDto)obj.ResponseObject);
        }
        public ActionResult Delete(int id)
        {
            var DAL = new DAL();
            var list = DAL.GetAllVehicles();
            return View("Details", list);
        }
        public ActionResult Create()
        {
            VehicleDetailsDto model = new VehicleDetailsDto();
            model.IsInCreateRecordMode = true;
            model.IsActive = true;
            return View("Details", model);
        }
        [HttpPost]
        public ActionResult Create(VehicleDetailsDto model)
        {
            if (model == null || string.IsNullOrEmpty(model.Name) || string.IsNullOrEmpty(model.RegistrationNumber)) throw new Exception("Bad format data passed.");

            model.IsInCreateRecordMode= true;
            var DAL = new DAL();
            var id = DAL.AddVehicle(model);
            
            if (id > 0) model = new VehicleDetailsDto(){IsInCreateRecordMode = true};

            ViewBag.Message = "Error";
            return View("Details", model);
        }
    }
}

BackofficeCar/BackofficeCar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
   <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>

</head>
<body>
<div class="wrapper">
        <div class="sidebar" data-image="/Content/themes/light_theme/img/sidebar-5.jpg">
            <!--<img src="../../Content/themes/light_theme/img/sidebar-5.jpg" alt="" />
        Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

        Tip 2: you can also add an image using data-image tag
    -->
            <div class="sidebar-wrapper">
                <div class="logo">
                    @Html.ActionLink(UIString.AppName, "Index", "Home", null, new {@class = "simple-text"})
                </div>
                <ul class="nav">
                    <li class="nav-item active">
                        @Html.ActionLink("Home", "Index", "Home", null, new {@class = "nav-link"})
                    </li>
                    <li>@Html.ActionLink("Manage Vehicles", "Index", "ManageVehicles", null, new {@class = "nav-link"})</li>
                    <li>@Html.ActionLink("Users", "Index", "ManageUsers", null, new {@class = "nav-link"})</li>

                    @*@if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin", null, new {@class = "nav-link"})</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin", null, new {@class = "nav-link"})</li>
                    }*@
                    <li>
                          @Html.Partial("_LoginPartial")
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            
            <!-- End Navbar -->
            <div class="content">
                <div class="container-fluid">
    @RenderBody()
                    
                </div>
            </div>
            <footer class="footer">
                <div class="container">
                    <nav>
                        <p class="copyright text-center">
                            &copy; @DateTime.Now.Year <a href="http://salikchughtai.com" target="_blank">Salik Chughtai</a>
                        </p>
                    </nav>
                </div>
                
            </footer>
        </div>
    </div>


@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

BackofficeCar/BackofficeCar/Views/Shared/_LayoutLight.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
   <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>

</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>